### ISSUE TITLE
extractPeaks(decodedData, 10000, true, 0, 0); doesn't return empty peaks

### ISSUE THREAD

**Issue by a3626a** [naomiaro/webaudio-peaks#2]
`extractPeaks(decodedData, 10000, true, 1, 1);` returns empty peaks
but `extractPeaks(decodedData, 10000, true, 0, 0);` does not. (gives peaks for the entire buffer)
>I think `extractPeaks(decodedData, 10000, true, 0, 0)` should return emtpy peaks. If you just think it is perfectly normal `extractPeaks(decodedData, 10000, true, 0, 0)` to return peaks for the entire buffer, I will just close this issue

it is because :
https://github.com/naomiaro/webaudio-peaks/blob/354c143494ee32a61d5675fcca25cc54755c9e60/index.js#L128-L141

`cueOut = cueOut || channel.length;` is `channel.length` when `cueOut == 0`. I think it can be changed into `cueOut = cueOut != undefined ? cueOut : channel.length;`

**Comment by naomiaro** [comment]
Hello!

Yes, this looks like it definitely should be updated to return zero peaks. Hopefully I can update this sometime soon.
